CREATE TABLE USERS (
    USERNAME VARCHAR(64) PRIMARY KEY,
    PASSWORD VARCHAR(64) NOT NULL,
    SALT VARCHAR(64) NOT NULL
);

CREATE TABLE USER_SCORE (
    USERNAME VARCHAR(64) REFERENCES USERS(USERNAME),
    WPM INT NOT NULL,
    ACCURACY INT NOT NULL,
    ELAPSED_TIME INT NOT NULL,
    DATE TIMESTAMP NOT NULL
);

CREATE TABLE USER_OPTIONS (
    USERNAME VARCHAR(64) REFERENCES USERS(USERNAME),
    TOKEN_DURATION INT DEFAULT 1800,
    DEAFAULT_THEME VARCHAR(64) DEFAULT 'dark',
    DISPLAY_NAME VARCHAR(255) NOT NULL
);
